name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test React frontend
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: |
        cd Task4
        npm install
        npm run build
        npm run test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Swagger server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /var/www/swagger-server
          git pull
          npm install
          npm run start

    - name: Deploy React frontend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /var/www/task4
          git pull
          npm install
          npm run build
